import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {connect} from './cdp.mjs';
const c=await connect(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),results={};
async function wait(expression){for(let i=0;i<160;i++){if(await c.evaluate(expression))return;await sleep(50);}throw Error('Timeout: '+expression);}
async function click(selector){await c.evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(100);await wait('JSON.stringify(window.pixelPals.getAvatar().root.userData.pixelPals.state)===JSON.stringify(window.pixelPals.getState())');}
async function input(selector,value,event='input'){await c.evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});if(e.type==='checkbox')e.checked=${JSON.stringify(value)};else e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));}`);await sleep(100);}
try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1180,deviceScaleFactor:1,mobile:false});await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});await wait('!!window.pixelPals?.getAvatar()');c.events.length=0;
 await c.evaluate('if(window.pixelPals.getPerformance().running)document.querySelector("#play").click();document.querySelector("#camera-front").click();document.querySelector("[data-pattern]").closest("details").open=true;');
 await wait('[...document.querySelectorAll("[data-preview^=pattern]")].every(i=>i.complete&&i.naturalWidth>0)');
 assert.equal(await c.evaluate('document.querySelectorAll("[data-pattern]").length'),8);assert.equal(await c.evaluate('new Set([...document.querySelectorAll("[data-preview^=pattern]")].map(i=>i.src)).size'),8);
 assert.equal(await c.evaluate('document.querySelectorAll("[data-lashes]").length'),6);assert.equal(await c.evaluate('new Set([...document.querySelectorAll("[data-lashes] img")].map(i=>i.src)).size'),6);
 await click('[data-mouth=none]');assert.equal(await c.evaluate('window.pixelPals.getState().mouth'),'none');await click('#undo');assert.equal(await c.evaluate('window.pixelPals.getState().mouth'),'cat');
 await click('[data-pattern=muzzle]');await c.evaluate('window.__root=window.pixelPals.getAvatar().root;void(window.__headMap=window.pixelPals.getAvatar().face.material.map);');
 await input('[data-setting=patternX]',.6);await input('[data-setting=patternX]',.7,'change');assert.equal(await c.evaluate('window.pixelPals.getState().patternX'),.7);assert.ok(await c.evaluate('window.__root===window.pixelPals.getAvatar().root&&window.__headMap===window.pixelPals.getAvatar().face.material.map'));await click('#undo');assert.equal(await c.evaluate('window.pixelPals.getState().patternX'),0);
 for(const[key,value]of[['patternWidth',1.8],['patternHeight',.45],['patternY',-.6]]){await input('[data-setting='+key+']',value);await input('[data-setting='+key+']',value,'change');assert.equal(await c.evaluate('window.pixelPals.getState()['+JSON.stringify(key)+']'),value);}
 await click('#reset-pattern-position');assert.deepEqual(await c.evaluate('(({patternX,patternY,patternWidth,patternHeight})=>[patternX,patternY,patternWidth,patternHeight])(window.pixelPals.getState())'),[0,0,1,1]);
 for(const id of['upper','lower','both','outer','fan']){await click('[data-lashes='+id+']');assert.equal(await c.evaluate('window.pixelPals.getState().eyelashes'),id);}
 await input('[data-setting=lashX]',.5);await input('[data-setting=lashX]',.5,'change');await click('#reset-lash-position');assert.equal(await c.evaluate('window.pixelPals.getState().lashX'),0);
 await click('[data-tab=accessory]');for(const id of['whiskers','shade','sweat'])await click('[data-face-detail='+id+']');assert.deepEqual(await c.evaluate('window.pixelPals.getState().faceDecorations'),['whiskers','shade','sweat']);await click('[data-face-detail=shade]');assert.deepEqual(await c.evaluate('window.pixelPals.getState().faceDecorations'),['whiskers','sweat']);await click('#undo');assert.deepEqual(await c.evaluate('window.pixelPals.getState().faceDecorations'),['whiskers','shade','sweat']);await click('[data-face-detail=none]');assert.deepEqual(await c.evaluate('window.pixelPals.getState().faceDecorations'),[]);
 await click('[data-accessory=hat-beret]');await input('#position-accessory','hat','change');await input('[data-accessory-transform=x]',2.4);await input('[data-accessory-transform=x]',2.4,'change');assert.equal(await c.evaluate('window.pixelPals.getState().accessoryTransforms.hat.x'),2.4);await click('#reset-accessory-position');assert.equal(await c.evaluate('window.pixelPals.getState().accessoryTransforms.hat'),undefined);
 await click('#clear-accessories');await click('[data-tail=whale]');await input('[data-setting=tailLength]',1.8);await input('[data-setting=tailLength]',1.8,'change');await wait('window.pixelPals.getAvatar().root.userData.pixelPals.state.tailLength===1.8');assert.equal(await c.evaluate('window.pixelPals.getState().tailLength'),1.8);await input('[data-setting=tailThickness]',1.5);await input('[data-setting=tailThickness]',1.5,'change');await wait('window.pixelPals.getAvatar().root.userData.pixelPals.state.tailThickness===1.5');
 results.layer=await c.evaluate(`(async()=>{const{defaults}=await import('./avatar.js'),{faceTexture}=await import('./face.js'),{paintHeadTexture}=await import('./head-texture.js'),{validateState}=await import('./mmd.js');const s={...defaults,expression:'basic',eyeSize:1,blush:false,mouth:'none',eyelashes:'none',scars:[]};const plain=faceTexture(s),scar=faceTexture({...s,scars:[{x:30/128,y:43/96,size:.4,color:'#ff00ff',angle:0,width:1,height:1,type:'stitch'}]});const p=plain.image.getContext('2d').getImageData(60,86,1,1).data,q=scar.image.getContext('2d').getImageData(60,86,1,1).data;const all=scar.image.getContext('2d').getImageData(0,0,256,192).data;let outside=0;for(let i=0;i<all.length;i+=4)if(all[i]>220&&all[i+1]<60&&all[i+2]>220&&all[i+3]>200)outside++;const head=document.createElement('canvas');head.width=head.height=1024;paintHeadTexture(head,{...s,faceDeco:'shade',faceDecorations:['shade']});const data=head.getContext('2d').getImageData(120,591,790,2).data;let jump=0;for(let x=0;x<790;x++)for(let channel=0;channel<3;channel++)jump=Math.max(jump,Math.abs(data[x*4+channel]-data[(x+790)*4+channel]));plain.dispose();scar.dispose();return{underEye:[...p].every((x,i)=>x===q[i]),scarOutsideEye:outside,shadeAtlasBoundaryJump:jump,legacy:validateState({faceDeco:'sweat'},defaults).faceDecorations};})()`);
 assert.ok(results.layer.underEye);assert.ok(results.layer.scarOutsideEye>20);assert.ok(results.layer.shadeAtlasBoundaryJump<=3);assert.deepEqual(results.layer.legacy,['sweat']);
 await click('#reset-character');await click('[data-filter=soft]');await input('[data-setting=shading]',false,'change');await wait('window.pixelPals.getAvatar().root.userData.pixelPals.state.shading===false');
 await c.evaluate(`window.__dominant=()=>{const source=window.pixelPals.getRenderer().domElement,c=document.createElement('canvas');c.width=source.width;c.height=source.height;const ctx=c.getContext('2d');ctx.drawImage(source,0,0);const d=ctx.getImageData(0,0,c.width,c.height).data,colors=new Map();for(let i=0;i<d.length;i+=4)if(d[i+3]===255){const k=d[i]+','+d[i+1]+','+d[i+2];colors.set(k,(colors.get(k)||0)+1);}return[...colors].sort((a,b)=>b[1]-a[1])[0][0].split(',').map(Number);};window.__softColor=window.__dominant();`);
 await click('[data-filter=retro]');await sleep(200);
 results.pixels=await c.evaluate(`(()=>{const src=window.pixelPals.getRenderer().domElement,can=document.createElement('canvas');can.width=src.width;can.height=src.height;const ctx=can.getContext('2d');ctx.drawImage(src,0,0);const d=ctx.getImageData(0,0,can.width,can.height).data;let tiles=0,uniform=0;for(let y=0;y<can.height-1;y+=2)for(let x=0;x<can.width-1;x+=2){const offsets=[(y*can.width+x)*4,(y*can.width+x+1)*4,((y+1)*can.width+x)*4,((y+1)*can.width+x+1)*4];if(offsets.every(i=>d[i+3]===255)){tiles++;if(offsets.every(i=>[0,1,2].every(k=>d[i+k]===d[offsets[0]+k])))uniform++;}}return{softColor:window.__softColor,retroColor:window.__dominant(),uniformTiles:uniform/tiles,tiles,cornerAlpha:d[3],nativeWidth:can.width,stageWidth:document.querySelector('#stage').clientWidth,scanlines:getComputedStyle(document.querySelector('#stage'),'::after').content};})()`);
 assert.ok(results.pixels.softColor.every((x,i)=>Math.abs(x-results.pixels.retroColor[i])<=2),JSON.stringify(results.pixels));assert.ok(results.pixels.uniformTiles>.96);assert.equal(results.pixels.cornerAlpha,0);assert.equal(results.pixels.nativeWidth,results.pixels.stageWidth);assert.equal(results.pixels.scanlines,'none');
 const sheets=await c.evaluate(`(async()=>{const T=await import('./vendor/three.module.js'),{defaults,buildAvatar,disposeAvatar}=await import('./avatar.js'),{createStudioLighting,applyStudioLighting}=await import('./lighting.js'),{patternOptions}=await import('./patterns.js'),{lashOptions}=await import('./eyelashes.js'),{clearAccessories}=await import('./accessories.js');const r=new T.WebGLRenderer({alpha:true,antialias:true});r.setSize(210,230);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.02;const scene=new T.Scene(),lights=createStudioLighting(scene),camera=new T.OrthographicCamera(-1.05,1.05,1.15,-1.15,.1,30);function sheet(entries,columns,headOnly=true){const canvas=document.createElement('canvas');canvas.width=columns*210;canvas.height=Math.ceil(entries.length/columns)*255;const ctx=canvas.getContext('2d');ctx.fillStyle='#f4f1eb';ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<entries.length;i++){const[label,patch,angle='front']=entries[i],s={...defaults,...clearAccessories,species:'none',tail:'none',expression:'basic',blush:false,motion:'still',head:1,...patch},a=buildAvatar(s);applyStudioLighting(lights,s);scene.add(a.root);if(headOnly){a.root.traverse(o=>{if(o.isMesh&&o!==a.face)o.visible=false;});camera.position.set(0,1.48,6);camera.lookAt(0,1.48,0);}else{camera.left=-1.45;camera.right=1.45;camera.top=1.59;camera.bottom=-1.59;camera.position.fromArray({rear:[0,1.4,-6],side:[5,1.4,-.8],top:[2,5,-3],angle:[3,2,-5]}[angle]);camera.lookAt(0,.9,-.45);camera.updateProjectionMatrix();}r.render(scene,camera);const x=i%columns*210,y=Math.floor(i/columns)*255;ctx.drawImage(r.domElement,x,y);ctx.fillStyle='#766553';ctx.textAlign='center';ctx.font='13px sans-serif';ctx.fillText(label,x+105,y+247);scene.remove(a.root);disposeAvatar(a);}return canvas.toDataURL().split(',')[1];}const patterns=sheet(patternOptions.map(([id,name])=>[name,{facePattern:id,patternColor:'#ab927b'}]),8),lashes=sheet(lashOptions.map(([id,name])=>[name,{eyelashes:id}]),6),shade=sheet([['그늘 + 수염',{faceDecorations:['shade','whiskers'],faceDecoColor:'#6b8c98',bodyColor:'#424244',patternColor:'#e8ddcc',facePattern:'muzzle',expression:'shy'}]],1),whale=sheet([['후면',{tail:'whale'},'rear'],['측면',{tail:'whale'},'side'],['위쪽',{tail:'whale'},'top'],['비스듬히',{tail:'whale'},'angle'],['길이 1.8 / 두께 1.5',{tail:'whale',tailLength:1.8,tailThickness:1.5},'angle']],5,false);r.dispose();r.forceContextLoss();return{patterns,lashes,shade,whale};})()`);
 for(const[name,data]of Object.entries(sheets))await writeFile('tests/artifacts/'+name+'-refined.png',Buffer.from(data,'base64'));
 assert.equal(c.events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);
 results.ui='8 pattern previews, 6 lash previews, mouth none, multiple details, wide movement, live texture/undo, independent tail length/thickness';await writeFile('tests/artifacts/appearance-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));
}finally{c.close();}
