import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {connect} from './cdp.mjs';
const c=await connect(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),results={};
async function wait(expression){for(let i=0;i<200;i++){if(await c.evaluate(expression))return;await sleep(50);}throw Error('Timeout '+expression);}
async function click(selector){await c.evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(100);}
async function input(selector,value,event='input'){await c.evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));}`);await sleep(100);}
try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1180,deviceScaleFactor:1,mobile:false});await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});await wait('!!window.pixelPals?.getAvatar()');c.events.length=0;
 assert.equal(await c.evaluate('window.pixelPals.getState().speed'),1.5);await click('[data-tab=accessory]');await click('[data-face-detail=shade]');assert.equal(await c.evaluate('document.querySelector("#face-shade-controls").hidden'),false);
 await c.evaluate('void(window.__root=window.pixelPals.getAvatar().root);');for(const[key,value]of[['shadeOpacity',.8],['shadeSoftness',.3],['shadeY',-.15]]){await input('[data-setting='+key+']',value);await input('[data-setting='+key+']',value,'change');assert.equal(await c.evaluate('window.pixelPals.getState()['+JSON.stringify(key)+']'),value);}assert.ok(await c.evaluate('window.__root===window.pixelPals.getAvatar().root'));await click('#undo');assert.equal(await c.evaluate('window.pixelPals.getState().shadeY'),0);
 await click('[data-face-detail=shade]');assert.equal(await c.evaluate('document.querySelector("#face-shade-controls").hidden'),true);
 for(const[id,key]of[['earring-hoop','earrings'],['horns','horns'],['wings-angel','wings'],['ribbon-both','ribbon'],['clip-bar','hairClip']]){
  await click('[data-accessory='+id+']');await input('#position-accessory',key,'change');assert.ok(await c.evaluate('!!document.querySelector("[data-accessory-transform=gap]")'));await input('[data-accessory-transform=gap]',.3);await input('[data-accessory-transform=gap]',.3,'change');assert.equal(await c.evaluate('window.pixelPals.getState().accessoryTransforms['+JSON.stringify(key)+'].gap'),.3);await click('#undo');assert.equal(await c.evaluate('window.pixelPals.getState().accessoryTransforms['+JSON.stringify(key)+']'),undefined);await input('[data-accessory-transform=gap]',.2);await input('[data-accessory-transform=gap]',.2,'change');await click('#reset-accessory-position');assert.equal(await c.evaluate('window.pixelPals.getState().accessoryTransforms['+JSON.stringify(key)+']'),undefined);
 }
 results.render=await c.evaluate(`(async()=>{
  const T=await import('./vendor/three.module.js'),{defaults,buildAvatar,disposeAvatar,skinnedAvatar}=await import('./avatar.js'),{clearAccessories}=await import('./accessories.js'),{createStudioLighting,applyStudioLighting}=await import('./lighting.js'),{paintHeadTexture}=await import('./head-texture.js'),{facetMesh}=await import('./surface.js'),{GLTFExporter}=await import('./vendor/GLTFExporter.js');
  const r=new T.WebGLRenderer({alpha:true,antialias:true});r.setSize(320,370);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.02;const scene=new T.Scene(),lights=createStudioLighting(scene),camera=new T.OrthographicCamera(-1.55,1.55,1.79,-1.79,.1,30);
  const entries=[['고양이 귀걸이',{earrings:'hoop'},'front'],['강아지 귀걸이',{species:'puppy',earrings:'hoop'},'angle'],['나란한 핀',{hairClip:'bar'},'angle'],['양쪽 리본',{ribbon:'both'},'front'],['리본 측면',{ribbon:'both'},'side'],['머리 위 리본',{ribbon:'top'},'angle'],['호박 정면',{bodyCostume:'pumpkin'},'front'],['호박 측면',{bodyCostume:'pumpkin'},'angle'],['둥글게 말린 다람쥐 꼬리',{tail:'squirrel'},'tail'],['그늘 25%',{bodyColor:'#424244',facePattern:'muzzle',shadeOpacity:.25,faceDecorations:['shade','whiskers']},'front'],['그늘 60%',{bodyColor:'#e4dacb',shadeOpacity:.6,faceDecorations:['shade'],facePattern:'roundMuzzle'},'front'],['그늘 60% / 번짐 0',{bodyColor:'#e4dacb',shadeOpacity:.6,shadeSoftness:0,faceDecorations:['shade']},'front']];
  const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=1200;const ctx=canvas.getContext('2d');ctx.fillStyle='#f4f1eb';ctx.fillRect(0,0,canvas.width,canvas.height);
  let pumpkinRadii=[],pumpkinFront;for(let i=0;i<entries.length;i++){const[label,patch,angle]=entries[i],s={...defaults,...clearAccessories,blush:false,expression:'basic',tail:'none',motion:'still',...patch},a=buildAvatar(s);applyStudioLighting(lights,s);a.root.traverse(o=>facetMesh(o,true));scene.add(a.root);camera.position.fromArray({front:[0,1.35,6],angle:[3,2,6],side:[6,1.9,1.5],tail:[5,2,-3]}[angle]);camera.lookAt(0,1.28,angle==='tail'?-.4:0);r.render(scene,camera);const x=i%4*320,y=Math.floor(i/4)*400;ctx.drawImage(r.domElement,x,y);ctx.fillStyle='#766553';ctx.font='15px sans-serif';ctx.textAlign='center';ctx.fillText(label,x+160,y+389);
   if(patch.bodyCostume){if(angle==='front')pumpkinFront=r.domElement.toDataURL().split(',')[1];const g=a.root.getObjectByName('PumpkinCostume').children.find(o=>o.material.userData.colorSetting==='pumpkinColor').geometry,p=g.attributes.position;for(let j=0;j<p.count;j++)if(Math.abs(p.getY(j))<.001)pumpkinRadii.push(Math.hypot(p.getX(j),p.getZ(j)));}
   scene.remove(a.root);disposeAvatar(a);
  }
  const s={...defaults,...clearAccessories,earrings:'hoop',ribbon:'both',hairClip:'bar',bodyCostume:'pumpkin'},a=buildAvatar(s),exported=skinnedAvatar(a,s),glb=await new GLTFExporter().parseAsync(exported.root,{binary:true,onlyVisible:true});disposeAvatar(a);exported.geometry.dispose();
  function shade(opacity,softness=.75){const c=document.createElement('canvas');c.width=c.height=1024;paintHeadTexture(c,{...defaults,bodyColor:'#ffffff',faceDecorations:['shade'],shadeColor:'#000000',shadeOpacity:opacity,shadeSoftness:softness,expression:'basic',blush:false,mouth:'none'});const cx=c.getContext('2d');const sample=(x,y)=>cx.getImageData(Math.round((x+1)/2*1024),Math.round((2.6-y)/2*1024),1,1).data[0];return{top:sample(0,2),cheekBelow:sample(.6,.88),rear:cx.getImageData(512,15,1,1).data[0],upper:sample(.55,1.45),bottom:sample(.55,1.03)};}
  const report={pumpkinFront,sheet:canvas.toDataURL().split(',')[1],glbBytes:glb.byteLength,glbMagic:new TextDecoder().decode(new Uint8Array(glb,0,4)),pumpkinRadialRange:[Math.min(...pumpkinRadii),Math.max(...pumpkinRadii)],shadeOff:shade(0),shadeOn:shade(1),shadeSoft:shade(.6),shadeHard:shade(.6,0)};r.dispose();r.forceContextLoss();return report;
 })()`);
 await writeFile('tests/artifacts/attachments-refined.png',Buffer.from(results.render.sheet,'base64'));delete results.render.sheet;await writeFile('tests/artifacts/pumpkin-refined.png',Buffer.from(results.render.pumpkinFront,'base64'));delete results.render.pumpkinFront;
 assert.equal(results.render.glbMagic,'glTF');assert.ok(results.render.glbBytes>100000);assert.ok(results.render.pumpkinRadialRange[1]-results.render.pumpkinRadialRange[0]>.2);assert.equal(results.render.shadeOff.top,255);assert.ok(results.render.shadeOn.top<30);assert.equal(results.render.shadeOn.rear,255);assert.equal(results.render.shadeOn.cheekBelow,255);assert.ok(results.render.shadeSoft.bottom>results.render.shadeHard.bottom);
 assert.equal(c.events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);results.ui={shadeControls:true,pairGapControls:5,undoReset:true,defaultSpeed:1.5};await writeFile('tests/artifacts/attachment-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));
}finally{c.close();}
