import assert from 'node:assert/strict';
import {writeFile,readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';import {fileURLToPath}from'node:url';
import {connect} from './cdp.mjs';
import {unzipSync,strFromU8} from '../dist/vendor/fflate.module.js';
import {Writer} from '../dist/mmd.js';
const {Parser}=createRequire(import.meta.url)('../dist/vendor/mmdparser.cjs');
const c=await connect(),out='tests/artifacts';await mkdir(out,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(expression,timeout=20000){const start=Date.now();while(Date.now()-start<timeout){if(await c.evaluate(expression))return;await sleep(150);}throw new Error('Timed out: '+expression);}
const click=s=>c.evaluate(`document.querySelector(${JSON.stringify(s)}).click()`);
async function input(s,value,event='change'){await c.evaluate(`{const el=document.querySelector(${JSON.stringify(s)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));}`);await sleep(120);}
async function file(s,path){const {root}=await c.send('DOM.getDocument');const {nodeId}=await c.send('DOM.querySelector',{nodeId:root.nodeId,selector:s});await c.send('DOM.setFileInputFiles',{nodeId,files:[fileURLToPath(new URL('../'+path,import.meta.url))]});await c.evaluate(`document.querySelector(${JSON.stringify(s)}).dispatchEvent(new Event('change',{bubbles:true}))`);await sleep(400);}
async function getDownload(ext){await wait(`window.__downloads.some(x=>x.name.endsWith(${JSON.stringify(ext)}))`,45000);const d=await c.evaluate(`(async()=>{const i=window.__downloads.findIndex(x=>x.name.endsWith(${JSON.stringify(ext)})),d=window.__downloads.splice(i,1)[0],bytes=new Uint8Array(await d.blob.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return{name:d.name,data:btoa(s)};})()`);const bytes=Buffer.from(d.data,'base64'),path=out+'/'+d.name;await writeFile(path,bytes);return {bytes,path,name:d.name};}
try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});await wait('!!window.pixelPals?.getRenderer()');c.events.length=0;
 await c.evaluate(`window.__downloads=[];window.__blobs=new Map();const originalURL=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=originalURL(blob);window.__blobs.set(url,blob);return url;};const originalClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download){window.__downloads.push({name:this.download,blob:window.__blobs.get(this.href)});}else originalClick.call(this);};`);
 assert.equal(await c.evaluate(`document.querySelectorAll('[data-preset]').length`),0);
 assert.equal(await c.evaluate(`document.querySelectorAll('[data-expression]').length`),24);
 for(const eye of['dot','spiral','heart','slit','button','teary']){await click(`[data-expression="${eye}"]`);await sleep(110);assert.equal(await c.evaluate('window.pixelPals.getState().expression'),eye);}
 await click('[data-setting="independentEyes"]');await input('[data-setting="rightExpression"]','star');assert.equal(await c.evaluate('window.pixelPals.getState().rightExpression'),'star');assert.equal(await c.evaluate('window.pixelPals.getState().independentEyes'),true);await click('#reset-character');
 for(const f of['retro','lowpoly','sunset','soft']){await click(`[data-filter="${f}"]`);await sleep(150);assert.equal(await c.evaluate('window.pixelPals.getState().filter'),f);}
 await input('#head-slider',1.2,'input');await input('#head-slider',1.2);await click('#undo');await sleep(150);assert.equal(await c.evaluate('window.pixelPals.getState().head'),1);await click('#redo');await sleep(150);assert.equal(await c.evaluate('window.pixelPals.getState().head'),1.2);
 await click('[data-tab="accessory"]');await click('[data-accessory="glasses-square"]');await click('[data-accessory="headset"]');await sleep(200);assert.equal(await c.evaluate('window.pixelPals.getState().headset'),true);
 await click('[data-tab="studio"]');await click('#studio-enabled');await click('#studio-add-current');await click('#studio-add-current');await click('[data-formation="v"]');assert.equal(await c.evaluate('window.pixelPals.getStudio().actors.length'),3);await input('[data-actor-range="angle"]',35,'input');await input('#actor-motion','dance');
 await click('#save-project');const json=await getDownload('.json');const saved=JSON.parse(json.bytes);assert.equal(saved.studio.actors.length,3);assert.equal(saved.studio.actors[2].angle,35);await click('#studio-enabled');await click('#reset-character');await file('#project-file',json.path);assert.equal(await c.evaluate('window.pixelPals.getStudio().enabled'),true);assert.equal(await c.evaluate('window.pixelPals.getState().head'),1.2);await click('#studio-enabled');
 console.log('PASS editor, all filters, body adjustment, undo/redo, accessories and three-character JSON round-trip');
 await click('#export-pmx');const zip=await getDownload('.zip'),entries=unzipSync(zip.bytes);const pmx=entries['character.pmx'];const model=new Parser().parsePmx(pmx.buffer.slice(pmx.byteOffset,pmx.byteOffset+pmx.byteLength),true);assert.equal(model.metadata.boneCount,22);for(const t of model.textures)assert.ok(entries[t],t);assert.equal(model.metadata.modelName,saved.state.name);assert.equal(JSON.parse(strFromU8(entries['project.json'])).state.head,1.2);
 await click('#export-glb');const glb=await getDownload('.glb');const dv=new DataView(glb.bytes.buffer,glb.bytes.byteOffset,glb.bytes.byteLength);assert.equal(dv.getUint32(0,true),0x46546c67);const gt=JSON.parse(glb.bytes.subarray(20,20+dv.getUint32(12,true)).toString());assert.equal(gt.skins[0].joints.length,22);assert.ok(gt.meshes[0].primitives.every(p=>p.attributes.JOINTS_0!==undefined&&p.attributes.WEIGHTS_0!==undefined));
 await c.evaluate(`window.__glb=Uint8Array.from(atob(${JSON.stringify(glb.bytes.toString('base64'))}),x=>x.charCodeAt(0)).buffer`);
 const glbCheck=await c.evaluate(`(async()=>{const {GLTFLoader}=await import('./vendor/GLTFLoader.js'),result=await new GLTFLoader().parseAsync(window.__glb,'');let skins=0;result.scene.traverse(o=>{if(o.isSkinnedMesh)skins++;});return {skins,name:result.scene.children[0].userData.pixelPals.state.name};})()`);assert.ok(glbCheck.skins>0);assert.equal(glbCheck.name,saved.state.name);
 await click('#reset-character');await file('#project-file',glb.path);assert.equal(await c.evaluate('window.pixelPals.getState().head'),1.2);await click('#export-png');const png=await getDownload('.png');assert.equal(png.bytes.subarray(1,4).toString(),'PNG');
 console.log('PASS PMX ZIP with all textures, independent PMX parsing, rigged GLB parse/re-import and transparent PNG');
 const w=new Writer(),fixed=(s,n)=>{const b=new TextEncoder().encode(s);w.bytes([...b,...Array(n-b.length).fill(0)]);};fixed('Vocaloid Motion Data 0002',30);fixed('Prototype',20);w.u32(2);for(const frame of[0,30]){fixed('Head',15);w.u32(frame).vec([0,0,0]).vec([0,0,frame?Math.sin(.25):0,frame?Math.cos(.25):1]).bytes(Array(64).fill(20));}w.u32(0).u32(0).u32(0).u32(0);await writeFile(out+'/head.vmd',w.finish());await file('#motion-file',out+'/head.vmd');assert.equal(await c.evaluate('window.pixelPals.getExternalMotion()?.type'),'vmd');await sleep(500);assert.ok(await c.evaluate('Math.abs(window.pixelPals.getAvatar().bones[5].quaternion.z)>.01'));
 await file('#motion-file',out+'/Samba Dancing.fbx');await wait(`window.pixelPals.getExternalMotion()?.type==='fbx'`,30000);assert.ok(await c.evaluate('window.pixelPals.getExternalMotion().mapped.length>=15'));
 const beforeFbx=await c.evaluate('window.pixelPals.getAvatar().bones.map(b=>b.quaternion.toArray())');await sleep(280);const afterFbx=await c.evaluate('window.pixelPals.getAvatar().bones.map(b=>b.quaternion.toArray())');assert.ok(afterFbx.some((q,i)=>q.some((v,j)=>Math.abs(v-beforeFbx[i][j])>.001)));
 await writeFile(out+'/bad.vmd',Buffer.from('invalid'));await file('#motion-file',out+'/bad.vmd');assert.equal(await c.evaluate('window.pixelPals.getExternalMotion()?.type'),'fbx');await click('#clear-motion');
 await click('[data-tab="motion"]');await input('#record-duration',1);await input('#record-format','gif');await click('#record');const gif=await getDownload('.gif');assert.equal(gif.bytes.subarray(0,6).toString(),'GIF89a');await wait('!document.querySelector("#record").disabled');await input('#record-format','webm');await click('#record');const webm=await getDownload('.webm');assert.equal(webm.bytes.subarray(0,4).toString('hex'),'1a45dfa3');assert.ok(webm.bytes.length>1000);
 await c.evaluate(`window.__videoBytes=Uint8Array.from(atob(${JSON.stringify(webm.bytes.toString('base64'))}),x=>x.charCodeAt(0));`);
 const video=await c.evaluate(`(async()=>{const v=document.createElement('video');v.muted=true;v.src=URL.createObjectURL(new Blob([window.__videoBytes],{type:'video/webm'}));document.body.append(v);await new Promise((resolve,reject)=>{v.onloadeddata=resolve;v.onerror=()=>reject(new Error('WebM decode failed'));setTimeout(()=>reject(new Error('WebM decode timeout')),10000);});const result={width:v.videoWidth,height:v.videoHeight};await v.play();await new Promise(r=>setTimeout(r,220));result.time=v.currentTime;const c=document.createElement('canvas');c.width=8;c.height=8;c.getContext('2d').drawImage(v,0,0,8,8);result.pixels=[...c.getContext('2d').getImageData(0,0,8,8).data];v.pause();URL.revokeObjectURL(v.src);v.remove();return result;})()`);assert.ok(video.width>=900&&video.height>300);assert.ok(video.time>0);assert.ok(video.pixels.some((x,i)=>i%4!==3&&x>20));
 console.log('PASS VMD playback, official Three.js FBX sample retargeting, invalid motion preservation and GIF/WebM recording');
 await click('#reset-character');await click('[data-tab="character"]');if(await c.evaluate(`document.querySelector('#play').getAttribute('aria-label').includes('일시')`))await click('#play');await input('#timeline',0,'input');
 for(const[name,y]of[['front',0],['side',Math.PI/2],['back',Math.PI]]){await c.evaluate(`window.pixelPals.getAvatar().root.rotation.y=${y};document.querySelector('#camera-front').click()`);await sleep(180);const rect=await c.evaluate(`(()=>{const r=document.querySelector('#stage').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,scale:1};})()`);const shot=await c.send('Page.captureScreenshot',{format:'png',clip:rect});await writeFile(out+'/'+name+'.png',Buffer.from(shot.data,'base64'));}
 await c.evaluate('window.pixelPals.getAvatar().root.rotation.y=0');const desktop=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(out+'/desktop.png',Buffer.from(desktop.data,'base64'));
 await c.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(300);assert.ok(await c.evaluate('document.documentElement.scrollWidth<=innerWidth'));assert.ok(await c.evaluate(`(()=>{const r=document.querySelector('#stage').getBoundingClientRect();return r.width>300&&r.height>300;})()`));assert.equal(await c.evaluate(`getComputedStyle(document.querySelector('.expression-grid')).display`),'grid');assert.ok(await c.evaluate(`(()=>{const buttons=[...document.querySelectorAll('[data-expression]')];return buttons.length===24&&buttons.every(b=>{const r=b.getBoundingClientRect();return r.width>65&&r.left>=0&&r.right<=innerWidth;});})()`));const mobile=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(out+'/mobile.png',Buffer.from(mobile.data,'base64'));
 assert.equal(c.events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);console.log('PASS front/side/back snapshots, 390px mobile layout and zero uncaught runtime exceptions');
 await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
}finally{c.close();}
