import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {connect} from './cdp.mjs';
const c=await connect(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(expression){for(let i=0;i<200;i++){if(await c.evaluate(expression))return;await sleep(50);}throw new Error('Timeout '+expression);}
async function click(selector){await c.evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await wait('JSON.stringify(window.pixelPals.getAvatar().root.userData.pixelPals.state)===JSON.stringify(window.pixelPals.getState())');}
try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1180,deviceScaleFactor:1,mobile:false});await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});await wait('!!window.pixelPals?.getAvatar()');c.events.length=0;
 await c.evaluate('document.querySelector("[data-pattern]").closest("details").open=true');await click('[data-tab="accessory"]');await wait('[...document.querySelectorAll("[data-preview]")].every(i=>i.complete&&i.naturalWidth>0)');
 const counts=await c.evaluate(`({accessories:document.querySelectorAll('[data-accessory]').length,tails:document.querySelectorAll('[data-tail]').length,images:document.querySelectorAll('[data-preview]').length,unique:new Set([...document.querySelectorAll('[data-accessory] img')].map(i=>i.src)).size})`);assert.deepEqual(counts,{accessories:35,tails:15,images:94,unique:35});
 const catalog=await c.evaluate(`(async()=>{const{accessoryOptions}=await import('./accessories.js');return accessoryOptions;})()`);
 for(const a of catalog){await click(`[data-accessory="${a.id}"]`);const s=await c.evaluate('window.pixelPals.getState()');assert.equal(s[a.key],a.value,a.id);if(a.styleKey)assert.equal(s[a.styleKey],a.styleValue,a.id);assert.equal(await c.evaluate(`document.querySelector('[data-accessory="${a.id}"]').getAttribute('aria-pressed')`),'true');await click(`[data-accessory="${a.id}"]`);assert.equal(await c.evaluate(`window.pixelPals.getState()[${JSON.stringify(a.key)}]`),typeof a.value==='boolean'?false:'none');}
 for(const id of ['halo','horns','hat-beanie','glasses-round','wings-angel','mug','pumpkin'])await click(`[data-accessory="${id}"]`);
 const prior=await c.evaluate('window.pixelPals.getState()');await click('#clear-accessories');assert.equal(await c.evaluate('document.querySelectorAll("[data-accessory][aria-pressed=true]").length'),0);await click('#undo');assert.deepEqual(await c.evaluate('window.pixelPals.getState()'),prior);
 await click('#randomize');const random=await c.evaluate('window.pixelPals.getState()');await click('#reset-random');const defaults=await c.evaluate(`(async()=>{const{defaults}=await import('./avatar.js');return defaults;})()`);assert.deepEqual(await c.evaluate('window.pixelPals.getState()'),defaults);await click('#undo');assert.deepEqual(await c.evaluate('window.pixelPals.getState()'),random);await click('#reset-random');
 // Test a real MP4 container and browser decoding, rather than its suffix alone.
 await c.evaluate(`window.__media=[];const original=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{window.__media.push(blob);return original(blob);};HTMLAnchorElement.prototype.click=function(){window.__mediaName=this.download;};document.querySelector('[data-motion=wave]').click();document.querySelector('#record-duration').value='2';document.querySelector('#record-format').value='mp4';document.querySelector('#record').click();`);
 await wait('window.__media.some(b=>b.type.startsWith("video/mp4"))');await wait('!document.querySelector("#record").disabled');
 const movie=await c.evaluate(`(async()=>{const blob=window.__media.find(b=>b.type.startsWith('video/mp4')),bytes=new Uint8Array(await blob.arrayBuffer()),video=document.createElement('video');video.muted=true;video.src=URL.createObjectURL(blob);document.body.append(video);await new Promise((res,rej)=>{video.onloadeddata=res;video.onerror=()=>rej(new Error('MP4 failed to decode'));setTimeout(()=>rej(new Error('MP4 decode timeout')),10000);});const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');async function at(t){await new Promise((res,rej)=>{video.onseeked=res;video.onerror=()=>rej(Error('Video seek failed'));video.currentTime=t;setTimeout(()=>rej(Error('Seek timeout')),10000);});ctx.drawImage(video,0,0,128,128);return [...ctx.getImageData(0,0,128,128).data];}const first=await at(.05),last=await at(.85);let changed=0;for(let i=0;i<last.length;i++)if(Math.abs(first[i]-last[i])>5)changed++;const result={width:video.videoWidth,height:video.videoHeight,time:video.currentTime,changed,name:window.__mediaName,type:blob.type};video.pause();video.remove();let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return{...result,data:btoa(text)};})()`);
 const bytes=Buffer.from(movie.data,'base64');assert.equal(bytes.subarray(4,8).toString(),'ftyp');assert.ok(movie.name.endsWith('.mp4'));assert.ok(movie.width>=900&&movie.time>0&&movie.changed>10,JSON.stringify({...movie,data:undefined}));await writeFile('tests/artifacts/verified-motion.mp4',bytes);
 // A paused scene should stop drawing until the model or camera changes.
 if(await c.evaluate('window.pixelPals.getPerformance().running'))await click('#play');await sleep(1600);const frames=await c.evaluate(`(async()=>{const r=window.pixelPals.getRenderer(),first=r.info.render.frame;await new Promise(v=>setTimeout(v,1000));return r.info.render.frame-first;})()`);assert.equal(frames,0);await click('#zoom-in');await sleep(150);
 const shot=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile('tests/artifacts/catalog-ui.png',Buffer.from(shot.data,'base64'));
 assert.equal(c.events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);console.log('PASS',JSON.stringify({counts,clearUndo:true,resetUndo:true,mp4:{...movie,data:undefined},pausedFrames:frames}));
}finally{c.close();}
