import {writeFile} from 'node:fs/promises';import {connect} from './cdp.mjs';
const c=await connect();try{
 await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});for(let i=0;i<200;i++){if(await c.evaluate('!!window.pixelPals?.getAvatar()'))break;await new Promise(r=>setTimeout(r,50));}
 const result=await c.evaluate(`(async()=>{
 const T=await import('./vendor/three.module.js'),{buildAvatar,defaults,disposeAvatar,poseAvatar}=await import('./avatar.js'),{clothingPatch}=await import('./clothing-options.js'),{createStudioLighting,applyStudioLighting}=await import('./lighting.js');
 const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(440,490);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;
 const scene=new T.Scene();scene.background=new T.Color('#f3f0e9');const rig=createStudioLighting(scene);applyStudioLighting(rig,{...defaults,shadeStrength:.3});const camera=new T.OrthographicCamera(-1.22,1.22,1.36,-1.36,.1,30);
 const entries=[['tee',clothingPatch('tee'),0,0],['raglan',clothingPatch('raglan'),.8,0],['suit',clothingPatch('suit'),0,0],['uniform',clothingPatch('uniform'),.5,0],['hood front',clothingPatch('hoodieUp'),0,0],['hood side',clothingPatch('hoodieUp'),1.3,0],['helmet front',{...clothingPatch('spacesuit'),spaceHelmet:true},0,0],['helmet side',{...clothingPatch('spacesuit'),spaceHelmet:true},1.2,0],['helmet back',{...clothingPatch('spacesuit'),spaceHelmet:true},Math.PI,0],['electric',{guitar:true,guitarStyle:'electric',guitarColor:'#91a8af'},.2,0],['shades',{glasses:true,glassesStyle:'sunglasses'},.8,0],['drink peak',{clothing:'cardigan',motion:'picnicDrink'},.3,3],['book',{clothing:'cardigan',motion:'readTogether'},.8,1.5],['syringe',{motion:'syringeHold'},.3,1.5],['guitar play',{motion:'guitarPlay',guitarStyle:'electric'},.3,1.5]];
 const sheet=document.createElement('canvas');sheet.width=1320;sheet.height=2590;const ctx=sheet.getContext('2d');ctx.fillStyle='#f3f0e9';ctx.fillRect(0,0,sheet.width,sheet.height);const metrics=[];
 for(let i=0;i<entries.length;i++){const[label,patch,angle,time]=entries[i],start=performance.now(),a=buildAvatar({...defaults,expression:'basic',tail:'none',...patch});scene.add(a.root);poseAvatar(a,patch.motion??'still',time,1);a.root.rotation.y=angle;camera.position.set(0,1.75,7);camera.lookAt(0,1.35,0);renderer.render(scene,camera);ctx.drawImage(renderer.domElement,i%3*440,Math.floor(i/3)*518);ctx.fillStyle='#776758';ctx.font='18px sans-serif';ctx.textAlign='center';ctx.fillText(label,i%3*440+220,Math.floor(i/3)*518+512);metrics.push({label,ms:Math.round(performance.now()-start),triangles:renderer.info.render.triangles});scene.remove(a.root);disposeAvatar(a);}
 renderer.dispose();return{image:sheet.toDataURL().split(',')[1],metrics};})()`);
 await writeFile('tests/artifacts/construction-review.png',Buffer.from(result.image,'base64'));delete result.image;console.log(JSON.stringify(result));
}finally{c.close();}
