import {writeFile} from 'node:fs/promises';import {connect} from './cdp.mjs';import assert from 'node:assert/strict';
const c=await connect();try{
 await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});for(let i=0;i<200;i++){if(await c.evaluate('!!window.pixelPals?.getAvatar()'))break;await new Promise(r=>setTimeout(r,50));}
 const data=await c.evaluate(`(async()=>{
 const T=await import('./vendor/three.module.js'),{buildAvatar,defaults,disposeAvatar,poseAvatar,skinnedAvatar}=await import('./avatar.js'),{clothingPatch}=await import('./clothing-options.js'),{createStudioLighting,applyStudioLighting}=await import('./lighting.js'),{GLTFExporter}=await import('./vendor/GLTFExporter.js');
 const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(360,400);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;
 const scene=new T.Scene();scene.background=new T.Color('#f3f0e9');const rig=createStudioLighting(scene);applyStudioLighting(rig,{...defaults,shadeStrength:.25});const camera=new T.OrthographicCamera(-1.5,1.5,1.667,-1.667,.1,30);
 const entries=[['후드 정면',clothingPatch('hoodieUp'),0],['후드 옆',clothingPatch('hoodieUp'),.9],['후드 뒤',clothingPatch('hoodieUp'),Math.PI],['헬멧 정면',{...clothingPatch('spacesuit'),spaceHelmet:true},0],['헬멧 옆',{...clothingPatch('spacesuit'),spaceHelmet:true},.9],['헬멧 뒤',{...clothingPatch('spacesuit'),spaceHelmet:true},Math.PI],['일렉기타',{guitar:true,guitarStyle:'electric',guitarColor:'#91a8af'},0],['햄버거 의상',{bodyCostume:'burger'},.4],['노트북 화면 방향',{laptop:true},.45],['헤드셋 동작',{...clothingPatch('hoodie'),motion:'musicListen'},0],['헤드셋 동작 옆',{...clothingPatch('hoodie'),motion:'musicListen'},.65],['선글라스',{glasses:true,glassesStyle:'sunglasses'},0],['물방울 선글라스',{glasses:true,glassesStyle:'dropSunglasses'},0],['눈물 안경 둥근',{glasses:true,glassesStyle:'tearRound'},0],['눈물 안경 사각',{glasses:true,glassesStyle:'tearSquare'},0],['커다란 주사기',{syringe:true},.12],['주사기 모션',{motion:'syringeHold'},.12],['귀가 나오는 후드',{...clothingPatch('hoodieUp'),hoodEarMode:'outside'},.12]];
 const sheet=document.createElement('canvas');sheet.width=1080;sheet.height=2604;const ctx=sheet.getContext('2d');ctx.fillStyle='#f3f0e9';ctx.fillRect(0,0,sheet.width,sheet.height);
 for(let i=0;i<entries.length;i++){const[label,patch,angle]=entries[i],a=buildAvatar({...defaults,expression:'basic',tail:'none',...patch});scene.add(a.root);poseAvatar(a,patch.motion??'still',.8,1);a.root.rotation.y=angle;camera.position.set(0,2.2,7);camera.lookAt(0,1.36,0);renderer.render(scene,camera);ctx.drawImage(renderer.domElement,i%3*360,Math.floor(i/3)*434);ctx.fillStyle='#776758';ctx.font='17px sans-serif';ctx.textAlign='center';ctx.fillText(label,i%3*360+180,Math.floor(i/3)*434+423);scene.remove(a.root);disposeAvatar(a);}
 const a=buildAvatar({...defaults,...clothingPatch('hoodieUp'),guitar:true,guitarStyle:'electric',earrings:'cuffs',earringSide:'right'}),model=skinnedAvatar(a,defaults),glb=await new GLTFExporter().parseAsync(model.root,{binary:true,onlyVisible:true});disposeAvatar(a);model.geometry.dispose();model.root.traverse(o=>{if(o.skeleton)o.skeleton.dispose();});renderer.dispose();renderer.forceContextLoss();return{image:sheet.toDataURL().split(',')[1],glbMagic:new TextDecoder().decode(new Uint8Array(glb,0,4)),glbBytes:glb.byteLength};})()`);
 await writeFile('tests/artifacts/headgear-final.png',Buffer.from(data.image,'base64'));delete data.image;assert.equal(data.glbMagic,'glTF');assert.ok(data.glbBytes>100000);console.log(JSON.stringify(data));
}finally{c.close();}
