import test from 'node:test';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import {defaults,buildAvatar,collectModel,disposeAvatar,poseAvatar} from '../dist/avatar.js';
import * as T from '../dist/vendor/three.module.js';
import {exportPMX,validateState,parseVMD,Writer,vmdMapping,applyVMD} from '../dist/mmd.js';
import {speciesOptions,tailOptions,eyeOptions} from '../dist/options.js';
import {faceTexture} from '../dist/face.js';
const ctx={clearRect(){},quadraticCurveTo(){},fillRect(){},drawImage(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},bezierCurveTo(){},clip(){},stroke(){},ellipse(){},fill(){},save(){},restore(){},translate(){},scale(){},rotate(){},createLinearGradient(){return{addColorStop(){}};},createRadialGradient(){return{addColorStop(){}};}};
globalThis.document={createElement(){return{width:0,height:0,getContext:()=>ctx};}};
const{Parser}=createRequire(import.meta.url)('../dist/vendor/mmdparser.cjs');
test('paired ornaments change separation without accumulating movement or breaking serialization',async()=>{
 const{applyAccessoryTransforms,validateAccessoryTransforms}=await import('../dist/accessory-transforms.js');
 for(const[key,patch,nested,axis]of[['earrings',{earrings:'hoop'},false,'x'],['horns',{horns:true},false,'x'],['ribbon',{ribbon:'both'},false,'x'],['wings',{wings:'angel'},true,'x'],['hairClip',{hairClip:'bar'},true,'y']]){
  const s={...defaults,...patch},a=buildAvatar(s),group=a.root.getObjectByName('Accessory-'+key),nodes=nested?group.children[0].children:group.children;
  assert.equal(nodes.length,2,key);const before=nodes.map(n=>n.position.clone());
  const next={...s,accessoryTransforms:{[key]:{gap:.4}}};applyAccessoryTransforms(a,next);const moved=nodes.map(n=>n.position.clone());
  assert.ok(moved.every((p,i)=>Math.abs(Math.abs(p[axis]-before[i][axis])-.2)<1e-6),key);
  applyAccessoryTransforms(a,next);nodes.forEach((n,i)=>assert.ok(n.position.equals(moved[i])));
  applyAccessoryTransforms(a,s);nodes.forEach((n,i)=>assert.ok(n.position.equals(before[i])));a.root.traverse(o=>assert.doesNotThrow(()=>JSON.stringify(o.userData)));disposeAvatar(a);
 }
 assert.equal(validateAccessoryTransforms({earrings:{x:.1}}).earrings.gap,0);assert.throws(()=>validateAccessoryTransforms({earrings:{gap:3}}));
});
test('earring studs pierce actual ear surfaces across animal styles and head sizes',()=>{
 for(const[species]of speciesOptions)for(const head of[.75,1.3]){
  const a=buildAvatar({...defaults,species,head,earrings:'hoop'}),group=a.root.getObjectByName('Accessory-earrings'),targets=[];
  a.root.getObjectByName('AnimalEars')?.traverse(o=>{if(o.isMesh&&o.userData.role==='ears')targets.push(o);});if(!targets.length)targets.push(a.face);
  a.root.updateMatrixWorld(true);for(const e of group.children){const anchor=e.getWorldPosition(new T.Vector3()),ray=new T.Raycaster(new T.Vector3(anchor.x,anchor.y,4),new T.Vector3(0,0,-1)),hit=ray.intersectObjects(targets,false)[0];assert.ok(hit,species);assert.ok(Math.abs(anchor.z-hit.point.z)<.025,species+' attachment distance');}
  disposeAvatar(a);
 }
});
test('all 24 original eye styles accept independent eye shapes and survive project validation',()=>{assert.equal(eyeOptions.length,24);assert.equal(new Set(eyeOptions.map(x=>x[0])).size,24);for(const[expression]of eyeOptions){const s=validateState({...defaults,expression,independentEyes:true,rightExpression:'heart',oddEyes:true},defaults);const tex=faceTexture(s);assert.equal(tex.image.width,256);assert.equal(tex.image.height,192);assert.equal(s.expression,expression);assert.equal(s.rightExpression,'heart');tex.dispose();}assert.throws(()=>validateState({rightExpression:'unknown'},defaults));});
test('all 18 animal silhouettes produce finite geometry, normalized skinning and independently parsable PMX',()=>{for(const[species]of speciesOptions){const s={...defaults,species,detail:'verylow',head:1.14,body:1.2,legs:.85,glasses:true,hat:true,headset:true,oddEyes:true,horns:true,ribbon:'both',outline:true};const a=buildAvatar(s),data=collectModel(a);assert.equal(a.fromProvidedModel,true);assert.ok(data.vertices.every(Number.isFinite),species);assert.ok(data.indices.every(i=>i>=0&&i<data.vertices.length/3),species);for(let i=0;i<data.skinWeights.length;i+=4)assert.ok(Math.abs(data.skinWeights.slice(i,i+4).reduce((a,b)=>a+b,0)-1)<1e-5);const pmx=exportPMX(a,s).bytes;const parsed=new Parser().parsePmx(pmx.buffer.slice(pmx.byteOffset,pmx.byteOffset+pmx.byteLength),true);assert.equal(parsed.metadata.vertexCount,data.vertices.length/3);assert.equal(parsed.metadata.boneCount,22);assert.ok(parsed.metadata.textureCount>=1);assert.ok(parsed.materials.every(m=>m.textureIndex<parsed.metadata.textureCount));assert.equal(parsed.materials.reduce((n,m)=>n+m.faceCount,0),parsed.metadata.faceCount);assert.equal(parsed.bones.filter(b=>b.ik).length,2);assert.equal(parsed.metadata.rigidBodyCount,0);disposeAvatar(a);}});
test('skull and seated cone ears are closed surfaces in one skinned head mesh',()=>{for(const species of['cat','fox','wolf'])for(const detail of['verylow','low','high']){const a=buildAvatar({...defaults,species,detail}),g=a.face.geometry,edges=new Map();assert.equal(a.face.name,'SculptedHead');assert.equal(a.bones[5].children.some(x=>x.userData.role==='ears'),false);const pos=g.attributes.position;const key=i=>[pos.getX(i),pos.getY(i),pos.getZ(i)].map(v=>v.toFixed(6)).join(':');for(let i=0;i<pos.count;i+=3){const tri=[key(i),key(i+1),key(i+2)];for(let j=0;j<3;j++){const key=[tri[j],tri[(j+1)%3]].sort().join('|');edges.set(key,(edges.get(key)||0)+1);}}assert.ok([...edges.values()].every(n=>n===2));assert.ok([...g.attributes.position.array].every(Number.isFinite));disposeAvatar(a);}});
test('subdivision creates more curved low-poly head facets while keeping closed ear surfaces',()=>{const low=buildAvatar({...defaults,detail:'verylow'}),high=buildAvatar({...defaults,detail:'low'});assert.ok(high.face.geometry.attributes.position.count>low.face.geometry.attributes.position.count*3);disposeAvatar(low);disposeAvatar(high);});
test('axolotl gills follow the whole body color and respect a separate outer ear color',()=>{
 for(const[earSeparate,shading]of[[false,true],[true,true],[false,false],[true,false]]){
  const a=buildAvatar({...defaults,species:'axolotl',bodyColor:'#69617e',innerEarColor:'#eedddd',earColor:'#d79caa',earSeparate,shading}),gills=a.root.getObjectByName('AnimalEars').children;
  assert.equal(gills.length,6);for(const gill of gills)assert.equal(gill.material.color.getHexString(),earSeparate?'d79caa':'69617e');disposeAvatar(a);
 }
});
test('PMX serializes all 4 skin influences without dropping bone weights',()=>{const a=buildAvatar({...defaults,detail:'verylow'}),bytes=exportPMX(a,defaults).bytes;const parsed=new Parser().parsePmx(bytes.buffer,true);for(const v of parsed.vertices)assert.ok(Math.abs(v.skinWeights.reduce((a,b)=>a+b,0)-1)<1e-5);disposeAvatar(a);});
test('rounded limbs animate with the rig and the capped tail is included in exported geometry',()=>{
 const a=buildAvatar(defaults),plain=buildAvatar({...defaults,tail:'none'});assert.ok(collectModel(a).vertices.length>collectModel(plain).vertices.length+300);
 const body=a.root.getObjectByName('SculptedBody'),boots=[14,17].map(bone=>{const g=body.geometry;for(let i=0;i<g.attributes.position.count;i++)if(g.attributes.skinIndex.getX(i)===bone&&g.attributes.skinWeight.getX(i)>.5)return i;return -1;});assert.ok(boots.every(i=>i>=0));
 assert.ok(Math.abs(a.bones[14].getWorldPosition(new T.Vector3()).x-.147)<1e-5);
 const sample=()=>{a.root.updateMatrixWorld(true);body.skeleton.update();return boots.map(i=>body.applyBoneTransform(i,new T.Vector3().fromBufferAttribute(body.geometry.attributes.position,i)));};
 poseAvatar(a,'still',0);const rest=sample();poseAvatar(a,'walk',.4);const moved=sample();assert.ok(moved.some((v,i)=>v.distanceTo(rest[i])>.01));
 for(const motion of['wave','dance','walk','spin','hop']){poseAvatar(a,motion,.4);a.root.updateMatrixWorld(true);a.root.traverse(o=>{if(!o.isSkinnedMesh)return;o.skeleton.update();const p=o.geometry.attributes.position;for(let i=0;i<p.count;i+=33)assert.ok(o.applyBoneTransform(i,new T.Vector3().fromBufferAttribute(p,i)).toArray().every(Number.isFinite));});}
 disposeAvatar(a);disposeAvatar(plain);
});
test('character validation rejects invalid geometry, color and editable marks without altering the input',()=>{for(const input of[{head:NaN},{head:100},{bodyColor:'red'},{species:'unicorn'},{outlineWidth:-1},{dots:[{x:4,y:.5,size:.01,color:'#000000'}]},{scars:[{x:.5,y:.5,size:.1,color:'#000000',angle:NaN,type:'line'}]}])assert.throws(()=>validateState(input,defaults));const valid=validateState({dots:[{x:.3,y:.6,size:.015,color:'#aabbcc'}],species:'axolotl'},defaults);assert.equal(valid.species,'axolotl');assert.equal(valid.dots.length,1);assert.equal(defaults.dots.length,0);});
test('all 15 tails, small low-poly tufts and simultaneous accessories remain finite and exportable',()=>{
 assert.equal(tailOptions.length,15);
 for(const[tail]of tailOptions){const s=validateState({...defaults,tail,tailSize:1.35,tufts:'both',halo:true,haloColor:'#c6b089',wings:'devil',hat:true,hatStyle:'y2k',mug:true,bellySeparate:true,hairClip:'mixed',earrings:'hoop',horns:true,shading:false},defaults),a=buildAvatar(s),data=collectModel(a);assert.ok(data.vertices.every(Number.isFinite),tail);assert.ok(data.normals.every(Number.isFinite),tail);assert.ok(data.indices.every(i=>i>=0&&i<data.vertices.length/3));const parts=[];a.root.traverse(o=>{if(o.name==='Tail')parts.push(o);});assert.equal(parts.length,tail==='none'?0:1);assert.ok(data.materials.every(m=>m.isMeshBasicMaterial));assert.equal(a.root.getObjectByName('Halo').material.color.getHexString(),'c6b089');assert.ok(a.root.getObjectByName('MugCostume'));assert.equal(a.root.getObjectByName('Tufts').children.length,7);const exported=exportPMX(a,s).bytes,parsed=new Parser().parsePmx(exported.buffer,true);assert.equal(parsed.metadata.vertexCount,data.vertices.length/3);poseAvatar(a,'dance',.4);a.root.updateMatrixWorld(true);disposeAvatar(a);}
});
test('marks have no count limit; legacy scars gain proportions and new proportions validate',()=>{
 const dots=Array.from({length:100},(_,i)=>({x:(i%10)/10,y:Math.floor(i/10)/10,size:.005,color:'#70606d'}));
 const scars=Array.from({length:50},()=>({x:.4,y:.6,size:.1,color:'#985e6f',type:'stitch',angle:25,width:1.6,height:.7}));
 const state=validateState({dots,scars},defaults);assert.equal(state.dots.length,100);assert.equal(state.scars.length,50);assert.equal(state.scars[0].width,1.6);assert.equal(faceTexture(state).image.width,256);
 assert.equal(validateState({scars:[{...scars[0],width:undefined,height:undefined}]},defaults).scars[0].width,1);
 for(const bad of[0,4,NaN,'1'])assert.throws(()=>validateState({scars:[{...scars[0],width:bad}]},defaults));
});
function vmdFixture(){const w=new Writer();const fixed=(s,n)=>{const b=new TextEncoder().encode(s);w.bytes([...b,...Array(n-b.length).fill(0)]);};fixed('Vocaloid Motion Data 0002',30);fixed('Prototype',20);w.u32(2);for(const frame of[0,30]){fixed('Head',15);w.u32(frame).vec([0,0,0]).vec([0,0,frame?Math.sin(.25):0,frame?Math.cos(.25):1]);w.bytes(Array(64).fill(0).map((_,i)=>i%16<8?20:107));}w.u32(0).u32(0).u32(0).u32(0);return w.finish().buffer;}
test('VMD validates bounds, maps head motion, and interpolates rotations',()=>{const vmd=parseVMD(vmdFixture());assert.equal(vmd.duration,1);const mapped=vmdMapping(vmd);assert.equal(mapped[0].i,5);const a=buildAvatar(defaults);applyVMD(a,mapped,.5);assert.ok(Math.abs(a.bones[5].quaternion.z)>.05);assert.throws(()=>parseVMD(vmdFixture().slice(0,60)));assert.throws(()=>parseVMD(new ArrayBuffer(100)));disposeAvatar(a);});


test('merged body preserves every original vertex, normal, UV and skin weight',async()=>{const{bodyGeometry}=await import('../dist/body-sculpt.js'),{mergedBody}=await import('../dist/merged-body.js');for(const detail of['verylow','low','smooth']){const s={...defaults,detail,body:1.17,legs:.83},g=mergedBody(s,true),parts=[3,12,15,8,10].map(k=>{const a=bodyGeometry(k,s);if(!a.index)return a;const b=a.toNonIndexed();a.dispose();return b;});for(const name of['position','normal','uv','skinIndex','skinWeight']){const expected=parts.flatMap(p=>Array.from(p.attributes[name].array));assert.deepEqual(Array.from(g.attributes[name].array),expected);}assert.equal(g.groups.length,2);const clone=mergedBody(s,true);assert.notEqual(clone,g);assert.deepEqual(Array.from(clone.attributes.position.array),Array.from(g.attributes.position.array));parts.forEach(p=>p.dispose());g.dispose();clone.dispose();}});
test('all ears are solid; obsolete ear interior preferences do not reappear',()=>{assert.equal('innerEarColor'in defaults,false);assert.equal('innerEarColor'in validateState({innerEarColor:'#ff0000'},defaults),false);for(const[species]of speciesOptions){const a=buildAvatar({...defaults,species,bodyColor:'#223344',earSeparate:true,earColor:'#8899aa'});a.root.getObjectByName('AnimalEars')?.traverse(o=>{if(o.isMesh&&o.userData.role==='ears'){assert.equal(o.material.map,null);assert.equal(o.material.color.getHexString(),'8899aa');}});disposeAvatar(a);}});
test('color updates retain geometry and update independently colored accessories',async()=>{const{updateAvatarColors}=await import('../dist/colors.js'),s={...defaults,hat:true,hatStyle:'beanie',headset:true,wings:'angel',ribbon:'both',outline:true,tailSeparate:true,tuftSeparate:true,tufts:'pairedWisps'},a=buildAvatar(s),geometry=a.face.geometry,texture=a.face.material.map,next={...s,bodyColor:'#112233',hatColor:'#eeccee',headsetColor:'#557799',ribbonColor:'#bb9977',outlineColor:'#779955',tailColor:'#445566',tuftColor:'#8899aa'};updateAvatarColors(a,next);assert.equal(a.face.geometry,geometry);assert.equal(a.face.material.map,texture);a.root.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material]){const key=m.userData.colorSetting;if(key&&next[key]){const expected=new T.Color(next[key]);if(m.userData.colorScale)expected.multiplyScalar(m.userData.colorScale);assert.ok(m.color.equals(expected));}}});disposeAvatar(a);});
test('accessory transforms validate, preserve independent placements and stay attached to scaled heads',async()=>{const{applyAccessoryTransforms}=await import('../dist/accessory-transforms.js');for(const input of[{hat:{x:4}},{unknown:{x:0}},{hat:{scale:NaN}}])assert.throws(()=>validateState({accessoryTransforms:input},defaults));for(const head of[.75,1,1.3]){const s={...defaults,head,hat:true,ribbon:'both',headset:true,hairClip:'mixed'},a=buildAvatar(s),hat=a.root.getObjectByName('Accessory-hat'),ribbon=a.root.getObjectByName('Accessory-ribbon'),before=hat.getWorldPosition(new T.Vector3()),ribbonBefore=ribbon.getWorldPosition(new T.Vector3());applyAccessoryTransforms(a,{...s,accessoryTransforms:{hat:{x:.2,y:.1,z:.05}}});const after=hat.getWorldPosition(new T.Vector3());assert.ok(Math.abs(after.x-before.x-.2*head)<1e-5);assert.ok(after.y>before.y);assert.ok(ribbon.getWorldPosition(new T.Vector3()).distanceTo(ribbonBefore)<1e-6);disposeAvatar(a);}});
test('all smooth motions stay continuous; only retro intentionally holds frames',async()=>{const{motionNames}=await import('../dist/motions.js');const a=buildAvatar(defaults),sample=(motion,t)=>{poseAvatar(a,motion,t);return a.bones.map(b=>({p:b.position.clone(),q:b.quaternion.clone()}));};for(const motion of Object.keys(motionNames).filter(k=>k!=='retro')){const left=sample(motion,5.999),right=sample(motion,6.001);for(let i=0;i<left.length;i++){assert.ok(left[i].p.distanceTo(right[i].p)<.01,motion);assert.ok(left[i].q.angleTo(right[i].q)<.03,motion);}}const x=sample('retro',.01),y=sample('retro',.09),z=sample('retro',.14);assert.ok(x.every((v,i)=>v.p.equals(y[i].p)&&v.q.equals(y[i].q)));assert.ok(x.some((v,i)=>!v.p.equals(z[i].p)||!v.q.equals(z[i].q)));disposeAvatar(a);});
test('separate arm material and accessory placements survive PMX export',()=>{const s={...defaults,armSeparate:true,armColor:'#cc8899',hat:true,accessoryTransforms:{hat:{x:.12,y:.08,z:.04,scale:1.1,angle:7}}},a=buildAvatar(s),data=collectModel(a);assert.ok(data.materials.some(m=>m.color.getHexString()==='cc8899'));assert.ok(data.materials.every(m=>m.isMaterial));const pmx=exportPMX(a,s).bytes,parsed=new Parser().parsePmx(pmx.buffer.slice(pmx.byteOffset,pmx.byteOffset+pmx.byteLength),true);assert.equal(parsed.materials.reduce((n,m)=>n+m.faceCount,0),parsed.metadata.faceCount);disposeAvatar(a);});
test('mirrored padded ears, ribbon lobes and whale flukes retain outward surfaces',()=>{function volume(g){const p=g.attributes.position,ix=g.index?.array??Array.from({length:p.count},(_,i)=>i);let v=0;for(let i=0;i<ix.length;i+=3){const a=new T.Vector3().fromBufferAttribute(p,ix[i]),b=new T.Vector3().fromBufferAttribute(p,ix[i+1]),c=new T.Vector3().fromBufferAttribute(p,ix[i+2]);v+=a.dot(b.cross(c))/6;}return v;}for(const patch of[{species:'puppy'},{ribbon:'both'},{tail:'whale'}]){const a=buildAvatar({...defaults,...patch}),meshes=[];a.root.traverse(o=>{if(o.geometry?.type==='SphereGeometry'&&['ears','tail','ribbon'].includes(o.userData.role??o.parent?.userData.role))meshes.push(o);});assert.ok(meshes.length>=2);for(const mesh of meshes)assert.ok(volume(mesh.geometry)>0,'A mirrored surface faces inward');disposeAvatar(a);}});
test('all 52 accessory options and 14 tails support independent movement',async()=>{const{accessoryOptions,accessoryPatch,clearAccessories}=await import('../dist/accessories.js'),{applyAccessoryTransforms}=await import('../dist/accessory-transforms.js');const choices=accessoryOptions.map(a=>({key:a.key,patch:accessoryPatch(a)})).concat(tailOptions.filter(([id])=>id!=='none').map(([id])=>({key:'tail',patch:{tail:id}})));for(const{key,patch}of choices){const s={...defaults,...clearAccessories,tail:'none',...patch},a=buildAvatar(s),group=a.root.getObjectByName('Accessory-'+key);assert.ok(group,'Missing placement control for '+JSON.stringify(patch));const before=group.getWorldPosition(new T.Vector3());applyAccessoryTransforms(a,{...s,accessoryTransforms:{[key]:{x:.17,y:.12,z:.05,scale:1.1,angle:8}}});const after=group.getWorldPosition(new T.Vector3());assert.ok(Math.abs(after.x-before.x-.17)<1e-5,key);assert.ok(Math.abs(after.y-before.y-.12)<1e-5,key);assert.ok(Math.abs(after.z-before.z-.05)<1e-5,key);assert.equal(group.scale.x,1.1);disposeAvatar(a);}});
test('shade strength and all curved eyebrow choices survive validation and legacy projects',async()=>{const{eyebrowOptions}=await import('../dist/eyebrows.js'),{createStudioLighting,applyStudioLighting}=await import('../dist/lighting.js');assert.equal(defaults.shadeStrength,.25);assert.equal(validateState({name:'Old project'},defaults).shadeStrength,.25);for(const value of[-.1,1.1,NaN])assert.throws(()=>validateState({shadeStrength:value},defaults));for(const[eyebrow]of eyebrowOptions){const s=validateState({eyebrow,eyebrowY:.05,eyebrowSize:1.3,eyebrowColor:'#91565b'},defaults),a=buildAvatar(s);assert.equal(a.face.material.roughness,.95);disposeAvatar(a);}const scene=new T.Scene(),rig=createStudioLighting(scene);applyStudioLighting(rig,{...defaults,shadeStrength:0});assert.equal(rig.key.intensity,0);assert.equal(rig.fill.intensity,0);assert.equal(rig.hemi.intensity,0);applyStudioLighting(rig,{...defaults,shadeStrength:1});assert.equal(rig.ambient.intensity,0);assert.equal(rig.key.intensity,2.65);});
test('multiple face decorations and placement settings survive projects while old single selections migrate',()=>{
 assert.deepEqual(validateState({faceDeco:'sweat'},defaults).faceDecorations,['sweat']);
 const input={faceDecorations:['whiskers','shade','sweat'],mouth:'none',patternX:.7,patternY:-.6,patternWidth:1.8,patternHeight:.4,lashX:.5,eyebrowY:.4,accessoryTransforms:{hat:{x:2.4,y:-2.1,z:2.8,scale:2.5}}};
 const s=validateState(input,defaults);assert.deepEqual(validateState(JSON.parse(JSON.stringify(s)),defaults),s);assert.deepEqual(input.faceDecorations,['whiskers','shade','sweat']);
 for(const faceDecorations of['shade',['unknown'],['none'],['shade','shade']])assert.throws(()=>validateState({faceDecorations},defaults));
 assert.throws(()=>validateState({patternWidth:3},defaults));assert.throws(()=>validateState({tailLength:Infinity},defaults));
});
test('all tails change length independently of thickness; the whale fin is closed and exportable',()=>{
 const extent=s=>{const a=buildAvatar({...defaults,...s}),tail=a.root.getObjectByName('Tail');tail.updateWorldMatrix(true,true);const box=new T.Box3().setFromObject(tail);const size=box.getSize(new T.Vector3());disposeAvatar(a);return size;};
 for(const[tail]of tailOptions.filter(([id])=>id!=='none')){const short=extent({tail,tailLength:.5}),long=extent({tail,tailLength:2});assert.ok(long.z>short.z*1.5,tail);const thin=extent({tail,tailThickness:.5}),thick=extent({tail,tailThickness:2});assert.ok(thick.x*thick.y*thick.z>thin.x*thin.y*thin.z,tail);}
 const s={...defaults,tail:'whale',tailLength:1.8,tailThickness:1.5},a=buildAvatar(s),fin=a.root.getObjectByName('WhaleFluke'),g=fin.geometry,p=g.attributes.position,edges=new Map();let volume=0;
 const key=i=>[p.getX(i),p.getY(i),p.getZ(i)].map(v=>v.toFixed(5)).join(',');
 const ix=g.index?.array??Array.from({length:p.count},(_,i)=>i);for(let i=0;i<ix.length;i+=3){const ids=[ix[i],ix[i+1],ix[i+2]],v=ids.map(j=>new T.Vector3().fromBufferAttribute(p,j));volume+=v[0].dot(v[1].clone().cross(v[2]))/6;for(let j=0;j<3;j++){const k=[key(ids[j]),key(ids[(j+1)%3])].sort().join('|');edges.set(k,(edges.get(k)||0)+1);}}
 assert.ok(volume>0);assert.ok([...edges.values()].every(n=>n===2));assert.ok(Array.from(p.array).every(Number.isFinite));
 const parsed=new Parser().parsePmx(exportPMX(a,s).bytes.buffer,true);assert.equal(parsed.metadata.vertexCount,collectModel(a).vertices.length/3);disposeAvatar(a);
});
test('the squirrel brush is a full closed curled volume with finite PMX geometry',()=>{
 const s={...defaults,tail:'squirrel'},a=buildAvatar(s),g=a.root.getObjectByName('SquirrelBrush').geometry,p=g.attributes.position,ix=g.index.array,edges=new Map();let volume=0;
 for(let i=0;i<ix.length;i+=3){const ids=[ix[i],ix[i+1],ix[i+2]],v=ids.map(j=>new T.Vector3().fromBufferAttribute(p,j));volume+=v[0].dot(v[1].clone().cross(v[2]))/6;for(let j=0;j<3;j++){const key=[ids[j],ids[(j+1)%3]].sort((a,b)=>a-b).join(',');edges.set(key,(edges.get(key)||0)+1);}}
 assert.ok(volume>.02);assert.ok([...edges.values()].every(n=>n===2));assert.equal(p.count-edges.size+ix.length/3,2,'The curled volume must have no through-hole');assert.ok(Array.from(g.attributes.normal.array).every(Number.isFinite));assert.ok(new T.Box3().setFromObject(a.root.getObjectByName('Tail')).getSize(new T.Vector3()).x>.4);
 const bytes=exportPMX(a,s).bytes;assert.equal(new Parser().parsePmx(bytes.buffer,true).metadata.vertexCount,collectModel(a).vertices.length/3);disposeAvatar(a);
});
