import assert from 'node:assert/strict';
import{writeFile}from'node:fs/promises';
import{connect}from'./cdp.mjs';
const c=await connect();
try{
 c.events.length=0;await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});for(let i=0;i<60;i++){if(await c.evaluate('!!window.pixelPals?.getAvatar()'))break;await new Promise(r=>setTimeout(r,100));}
const result=await c.evaluate(`(async()=>{const T=await import('./vendor/three.module.js'),{buildAvatar,disposeAvatar,defaults}=await import('./avatar.js');const scene=new T.Scene();scene.background=new T.Color('#f3f0e9');scene.add(new T.HemisphereLight('#fff','#a49482',1.2));const light=new T.DirectionalLight('#fff8ef',2.2);light.position.set(-3,7,5);scene.add(light);const camera=new T.OrthographicCamera(-1.5,1.5,1.75,-1.75,.1,20);camera.position.set(0,1.50,8);camera.lookAt(0,1.50,0);const renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(360,420);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.outputColorSpace=T.SRGBColorSpace;const canvas=document.createElement('canvas');canvas.width=720;canvas.height=460;const ctx=canvas.getContext('2d');ctx.fillStyle='#f3f0e9';ctx.fillRect(0,0,720,460);const counts=[];for(const[index,tufts]of['wisps','pairedWisps'].entries()){const a=buildAvatar({...defaults,motion:'still',tufts});const g=a.root.getObjectByName('Tufts');counts.push(g.children.length);if(a.root.getObjectByName('ChestTufts'))throw new Error('Unwanted chest tuft mesh');scene.add(a.root);renderer.render(scene,camera);ctx.drawImage(renderer.domElement,index*360,0);ctx.fillStyle='#514d48';ctx.font='16px sans-serif';ctx.textAlign='center';ctx.fillText(index?'두 가닥씩 얇은 털 선':'띄엄띄엄 얇은 털 선',index*360+180,446);scene.remove(a.root);disposeAvatar(a);}renderer.dispose();return{counts,png:canvas.toDataURL().split(',')[1]};})()`);
assert.deepEqual(result.counts,[4,8]);await writeFile('tests/artifacts/sparse-lines-final.png',Buffer.from(result.png,'base64'));console.log('PASS sparse hair lines at four separated locations, 4 or 8 thin strands, no chest tuft mesh');
}finally{c.close();}
