import assert from 'node:assert/strict';import{writeFile}from'node:fs/promises';import{connect}from'./cdp.mjs';
const c=await connect();try{
 await c.send('Page.navigate',{url:'http://127.0.0.1:4178/'});await new Promise(r=>setTimeout(r,1800));
 const result=await c.evaluate(`(async()=>{
 const T=await import('./vendor/three.module.js'),{buildAvatar,disposeAvatar,defaults}=await import('./avatar.js'),{eyeOptions}=await import('./options.js'),{accessoryOptions,accessoryPatch,clearAccessories}=await import('./accessories.js');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setSize(220,260);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;const scene=new T.Scene();scene.background=new T.Color('#f3f0e9');scene.add(new T.HemisphereLight('#ffffff','#9d9181',.95));const key=new T.DirectionalLight('#fffaf2',2.35);key.position.set(-3,8,4);scene.add(key);const fill=new T.DirectionalLight('#efe9e0',.75);fill.position.set(4,3,-2);scene.add(fill);const camera=new T.OrthographicCamera(-1.63,1.63,1.925,-1.925,.1,30);camera.position.set(2,2.1,8);camera.lookAt(0,1.30,0);
 const sheet=(items,patch)=>{const canvas=document.createElement('canvas');canvas.width=1100;canvas.height=Math.ceil(items.length/5)*292;const ctx=canvas.getContext('2d');ctx.fillStyle='#f3f0e9';ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<items.length;i++){const[id,label]=items[i],a=buildAvatar({...defaults,...clearAccessories,motion:'still',...patch(id)});scene.add(a.root);renderer.render(scene,camera);ctx.drawImage(renderer.domElement,(i%5)*220,Math.floor(i/5)*292);ctx.fillStyle='#514d48';ctx.font='13px sans-serif';ctx.textAlign='center';ctx.fillText(label,(i%5)*220+110,Math.floor(i/5)*292+276);scene.remove(a.root);disposeAvatar(a);}return canvas.toDataURL().split(',')[1];};
 const accessory=sheet(accessoryOptions.map(a=>[a.id,a.label]),id=>accessoryPatch(accessoryOptions.find(a=>a.id===id)));
 const patterns=sheet([['none','무늬 없음'],['forehead','이마 물결'],['cheeks','볼 포인트'],['spots','작은 반점'],['mask','눈 마스크'],['muzzle','입 포인트'],['split','반쪽 컬러'],['outline','윤곽선'],['outlinedHat','비니 + 윤곽선']],id=>({species:'lop',patternColor:'#b89baa',facePattern:['outline','outlinedHat'].includes(id)?'none':id,outline:['outline','outlinedHat'].includes(id),hat:id==='outlinedHat',hatStyle:'beanie'}));
 const eyes=sheet(eyeOptions,id=>({expression:id}));
 const animals=sheet([['puppy','처진 강아지'],['uprightPuppy','쫑긋 강아지'],['chibiCat','치비 고양이'],['lop','늘어진 토끼'],['largeLop','큰 롭이어']],id=>({species:id,bodyColor:'#69617e',innerEarColor:'#f2dae1'}));
 renderer.setSize(480,480);camera.left=-.9;camera.right=.9;camera.top=.9;camera.bottom=-.9;camera.position.set(0,1.35,8);camera.lookAt(0,1.35,0);camera.updateProjectionMatrix();const dot=buildAvatar({...defaults,shading:false,tail:'none',blush:false,dots:[{x:.42,y:.74,size:.03,color:'#ff1000'}]});scene.add(dot.root);renderer.render(scene,camera);const canvas=document.createElement('canvas');canvas.width=canvas.height=480;const ctx=canvas.getContext('2d');ctx.drawImage(renderer.domElement,0,0);const p=ctx.getImageData(0,0,480,480).data;let x0=480,y0=480,x1=0,y1=0,count=0;for(let i=0;i<p.length;i+=4)if(p[i]>160&&p[i+1]<90&&p[i+2]<90){const x=i/4%480,y=Math.floor(i/4/480);x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);count++;}const dotRatio=(x1-x0+1)/(y1-y0+1),dotImage=canvas.toDataURL().split(',')[1];scene.remove(dot.root);disposeAvatar(dot);renderer.dispose();renderer.forceContextLoss();return{accessory,patterns,eyes,animals,dotImage,dotRatio,dotPixels:count};})()`);
 assert.ok(result.dotPixels>100&&Math.abs(result.dotRatio-1)<.09,JSON.stringify({ratio:result.dotRatio,pixels:result.dotPixels}));
 for(const key of['accessory','patterns','eyes','animals','dotImage'])await writeFile('tests/artifacts/'+key+'-verified.png',Buffer.from(result[key],'base64'));
 assert.equal(c.events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);console.log('PASS actual 35 accessory, 24 eye, pattern/outline and animal mesh renders; round dot aspect ratio',result.dotRatio);
}finally{c.close();}
