import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import * as T from '../dist/vendor/three.module.js';
import {defaults,buildAvatar,disposeAvatar,poseAvatar,collectModel} from '../dist/avatar.js';
import {clothingStyles,clothingPatch} from '../dist/clothing-options.js';
import {socialMotions} from '../dist/social-motion.js';
import {applyAccessoryTransforms} from '../dist/accessory-transforms.js';
import {exportPMX,validateState} from '../dist/mmd.js';
const context={clearRect(){},quadraticCurveTo(){},fillRect(){},drawImage(){},beginPath(){},closePath(){},moveTo(){},lineTo(){},bezierCurveTo(){},clip(){},stroke(){},ellipse(){},fill(){},save(){},restore(){},translate(){},scale(){},rotate(){},createLinearGradient(){return{addColorStop(){}};},createRadialGradient(){return{addColorStop(){}};}};
globalThis.document={createElement(){return{width:0,height:0,getContext:()=>context};}};
const {Parser}=createRequire(import.meta.url)('../dist/vendor/mmdparser.cjs');
function finite(a){a.root.updateMatrixWorld(true);a.root.traverse(o=>{if(!o.isMesh)return;for(const attr of Object.values(o.geometry.attributes))assert.ok([...attr.array].every(Number.isFinite),o.name);if(o.isSkinnedMesh){o.skeleton.update();const p=o.geometry.attributes.position;for(let i=0;i<p.count;i+=47)assert.ok(o.applyBoneTransform(i,new T.Vector3().fromBufferAttribute(p,i)).toArray().every(Number.isFinite),o.name);}});}
test('all 18 clothes follow the body rig, remain finite across poses and serialize to independently parsed PMX',()=>{
 assert.equal(clothingStyles.length,18);
 for(const style of clothingStyles){const s=validateState({...defaults,...clothingPatch(style.id),detail:'verylow'},defaults),a=buildAvatar(s),group=a.root.getObjectByName('Clothing');assert.ok(group,style.id);assert.ok(group.children.every(o=>o.isSkinnedMesh));for(const mesh of group.children){assert.equal(mesh.skeleton,a.face.skeleton);const w=mesh.geometry.attributes.skinWeight;for(let i=0;i<w.count;i++)assert.ok(Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)<1e-5);}
  for(const motion of ['wave','walk','picnicDrink','musicListen']){poseAvatar(a,motion,.7);finite(a);}
  const data=collectModel(a),bytes=exportPMX(a,s).bytes,parsed=new Parser().parsePmx(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),true);assert.equal(parsed.metadata.vertexCount,data.vertices.length/3);assert.ok(data.vertices.every(Number.isFinite));disposeAvatar(a);
 }
});
test('clothing placement changes actual attached skin vertices without accumulating deformation',()=>{const s={...defaults,clothing:'hoodieUp'},a=buildAvatar(s),g=a.root.getObjectByName('Clothing'),m=g.children[0],sample=()=>Array.from(m.geometry.attributes.position.array),before=sample();const next={...s,accessoryTransforms:{clothing:{x:.15,y:.10,z:.04,scale:1.12,angle:12}}};applyAccessoryTransforms(a,next);const after=sample();assert.notDeepEqual(after,before);applyAccessoryTransforms(a,next);assert.deepEqual(sample(),after);applyAccessoryTransforms(a,s);assert.deepEqual(sample(),before);finite(a);disposeAvatar(a);});
test('ear cuffs have two rings on a selected ear and support separation and scaled heads',()=>{for(const species of ['cat','fox','wolf','puppy','bunny'])for(const head of [.75,1.3]){const s={...defaults,species,head,earrings:'cuffs',earringSide:'right'},a=buildAvatar(s),g=a.root.getObjectByName('Accessory-earrings');assert.ok(g,species);assert.equal(g.children.length,1);assert.equal(g.children[0].children.length,2,species);const rings=g.children[0].children,old=rings.map(r=>r.position.y);applyAccessoryTransforms(a,{...s,accessoryTransforms:{earrings:{gap:.08}}});assert.ok(Math.abs(Math.abs(rings[0].position.y-old[0])-.04)<1e-5);finite(a);disposeAvatar(a);}});
test('all ten social motions work solo, reset hidden props, are continuous and do not leak stage props into model exports',()=>{
 assert.equal(socialMotions.size,10);const a=buildAvatar({...defaults,clothing:'pajamas'}),baseline=collectModel(a).vertices.length;
 for(const motion of socialMotions){poseAvatar(a,motion,1.2);finite(a);const first=a.bones.map(b=>b.getWorldPosition(new T.Vector3()));poseAvatar(a,motion,1.201);const next=a.bones.map(b=>b.getWorldPosition(new T.Vector3()));assert.ok(next.some((p,i)=>p.distanceTo(first[i])>1e-7),motion);assert.ok(next.every((p,i)=>p.distanceTo(first[i])<.02),motion+' continuity');assert.equal(collectModel(a).vertices.length,baseline,motion+' model export');}
 poseAvatar(a,'still',0);a.root.traverse(o=>{if(o.userData.motionProp)assert.equal(o.visible,false,o.name);});disposeAvatar(a);
});
test('new standalone props survive color, placement and PMX roundtrip',()=>{for(const patch of [{syringe:true},{guitar:true},{guitar:true,guitarStyle:'electric'},{laptop:true},{burger:true},{bodyCostume:'burger'},{sleepCap:true},{spaceHelmet:true},{glasses:true,glassesStyle:'sunglasses'},{glasses:true,glassesStyle:'dropSunglasses'},{glasses:true,glassesStyle:'tearRound'},{glasses:true,glassesStyle:'tearSquare'}]){const s=validateState({...defaults,...patch},defaults),a=buildAvatar(s);finite(a);const bytes=exportPMX(a,s).bytes;assert.ok(new Parser().parsePmx(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),true).metadata.vertexCount>0);disposeAvatar(a);}});

test('music listening keeps both hands below the face across head sizes',()=>{for(const head of [.75,1,1.3]){const a=buildAvatar({...defaults,head,clothing:'hoodie'});for(const t of [0,.3,.7,1.4,2.8]){poseAvatar(a,'musicListen',t);a.root.updateMatrixWorld(true);const chin=a.bones[5].localToWorld(new T.Vector3(0,.765-a.headOrigin[1],0)).y;for(const index of [9,13])assert.ok(a.bones[index].getWorldPosition(new T.Vector3()).y<chin-.05,'hand remains down');assert.equal(a.root.getObjectByName('MusicRaisedArm'),undefined);}disposeAvatar(a);}});
